% make paper figure names:

%%

if ~exist('paperfigures','dir')
    mkdir('paperfigures');
end

%%

oldNamesREG = {'Bacillus_subtilis_bonev','Bacillus_subtilis_expint','Bacillus_subtilis_radExp','3ModelCompare2',...
            'Micrococcus_luteus_bonev','Micrococcus_luteus_expint','Micrococcus_luteus_radExp','3ModelCompare1',...
            'BonevMCMC6200k','BonevMCMC4200k','ExpIntMCMC6200k','ExpIntMCMC4200k','radicalExpMCMC6200k','radicalExpMCMC4200k',...
            'ThreeModelExcisedData3','ThreeModelExcisedData2','ThreeModelExcisedData1',...
            'ThreeModelCompareConvex30','ThreeModelCompareConvex20','ThreeModelCompareConvex10',...
            'ThreeModelCompareConvex31','ThreeModelCompareConvex21','ThreeModelCompareConvex11',...
            'ThreeModelCompareConvex32','ThreeModelCompareConvex22','ThreeModelCompareConvex12',...
            };

newNamesREG = {'2A','2B','2C','2D',...
            '3A','3B','3C','3D',...    
            '4A','4B','4C','4D','4E','4F',...    
            '5A','5B','5C',...
            '6AL','6AC','6AR',...
            '6BL','6BC','6BR',...
            '6CL','6CC','6CR'};

N = length(newNamesREG);
for j = 1:N
    srcfile = ['./figures/',oldNamesREG{j},'.pdf'];
    destfile = ['./paperfigures/Figure',newNamesREG{j},'.pdf'];
    try
        movefile(srcfile,destfile);
        disp(['file moved: ',srcfile])
    catch
        disp(['file not found error: ',srcfile])
    end
end

